server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://tradesimx-backend-246532816778.europe-west10.run.app/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
