export const defaultBrokerConfig = {
  commissionPerTrade: Number(process.env.BROKER_COMMISSION_PER_TRADE ?? 1.5),
  feeRateBps: Number(process.env.BROKER_FEE_RATE_BPS ?? 1),
  baseSpreadBps: Number(process.env.BROKER_SPREAD_BPS ?? 8),
  baseSlippageBps: Number(process.env.BROKER_BASE_SLIPPAGE_BPS ?? 2),
  randomSlippageBps: Number(process.env.BROKER_RANDOM_SLIPPAGE_BPS ?? 4),
  sizeImpactBps: Number(process.env.BROKER_SIZE_IMPACT_BPS ?? 0.3),
  executionDelayMs: Number(process.env.BROKER_EXECUTION_DELAY_MS ?? 0),
  settlementDaysEquities: Number(process.env.BROKER_SETTLEMENT_DAYS ?? 1),
  initialMarginLong: Number(process.env.BROKER_INITIAL_MARGIN_LONG ?? 0.5),
  initialMarginShort: Number(process.env.BROKER_INITIAL_MARGIN_SHORT ?? 1.5),
  maintenanceMarginLong: Number(process.env.BROKER_MAINT_MARGIN_LONG ?? 0.25),
  maintenanceMarginShort: Number(process.env.BROKER_MAINT_MARGIN_SHORT ?? 0.3),
  shortBorrowDailyRate: Number(process.env.BROKER_SHORT_BORROW_DAILY_RATE ?? 0.0003),
  enforceMarketHours: process.env.BROKER_ENFORCE_MARKET_HOURS === "true",
  marketOpenHour: Number(process.env.BROKER_MARKET_OPEN_HOUR ?? 9),
  marketOpenMinute: Number(process.env.BROKER_MARKET_OPEN_MINUTE ?? 30),
  marketCloseHour: Number(process.env.BROKER_MARKET_CLOSE_HOUR ?? 16),
  marketCloseMinute: Number(process.env.BROKER_MARKET_CLOSE_MINUTE ?? 0),
  forceLiquidationEnabled: process.env.BROKER_FORCE_LIQUIDATION !== "false",
  seed: Number(process.env.BROKER_SEED ?? 1337),
};
