server.port=9090

# Actuator health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Broker Configuration
broker.commission-per-trade=1.50
broker.fee-rate-bps=1
broker.base-spread-bps=8
broker.base-slippage-bps=2
broker.random-slippage-bps=4
broker.size-impact-bps=0.3
broker.market-data-mode=replay

spring.datasource.url=jdbc:mariadb://mariadb_init:3306/demo_db
spring.datasource.username=demo_user
spring.datasource.password=demo_pass


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
